# Generated by Django 4.2.6 on 2025-09-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('interview_notes', models.TextField(blank=True, help_text='Common interview questions, key cultural topics, or technical areas to focus on for this company.')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
