# Generated by Django 5.2.4 on 2025-11-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('trait', models.CharField(choices=[('EI', 'Extraversion (E) vs. Introversion (I)'), ('SN', 'Sensing (S) vs. Intuition (N)'), ('TF', 'Thinking (T) vs. Feeling (F)'), ('JP', 'Judging (J) vs. Perceiving (P)')], max_length=2)),
                ('choice_a', models.CharField(max_length=200)),
                ('choice_b', models.CharField(max_length=200)),
            ],
        ),
    ]
