# Generated by Django 4.2.6 on 2026-01-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, help_text='Upload your resume (PDF only, max 5MB).', null=True, upload_to='resumes/'),
        ),
    ]
