# Generated by Django 4.2.6 on 2026-01-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='detailed_report',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
