# Generated by Django 4.2.6 on 2026-01-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_assessmentresult_detailed_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order of the question in the quiz.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
