# Generated by Django 4.2.6 on 2026-01-21 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_savedcompany_interviewsession_careerpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Language', 'Language'), ('Framework', 'Framework'), ('Tool', 'Tool'), ('Concept', 'Concept'), ('Role', 'Role'), ('Soft Skill', 'Soft Skill')], default='Concept', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.IntegerField(default=1, help_text='1-10 Scale')),
                ('learning_weeks', models.IntegerField(default=1, help_text='Estimated weeks to learn')),
                ('importance_score', models.FloatField(default=0.0, help_text='Calculated Centrality Score')),
            ],
        ),
        migrations.CreateModel(
            name='SkillSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate', models.FloatField(default=0.5, help_text='P(Skill|Hired) - Probability appearing in hired profiles')),
                ('failure_rate', models.FloatField(default=0.1, help_text='P(Skill|Rejected) - Probability appearing in rejected profiles')),
                ('demand_trend', models.CharField(choices=[('Rising', 'Rising'), ('Stable', 'Stable'), ('Falling', 'Falling')], default='Stable', max_length=20)),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_signal', to='core.skillnode')),
            ],
        ),
        migrations.CreateModel(
            name='SkillEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_time', models.IntegerField(default=1, help_text='Transition time cost')),
                ('weight_difficulty', models.IntegerField(default=1, help_text='Transition difficulty cost')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.skillnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.skillnode')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
