# Generated by Django 4.2.6 on 2026-01-21 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_skillnode_skillsignal_skilledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerpath',
            name='is_predefined',
            field=models.BooleanField(default=False, help_text='If True, this is a system-defined path for all users.'),
        ),
        migrations.AlterField(
            model_name='careerpath',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to=settings.AUTH_USER_MODEL),
        ),
    ]
