# Generated by Django 4.2.6 on 2026-01-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_therapysession'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, help_text='Industry sector (e.g. Tech, Finance, Healthcare)', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='tech_stack',
            field=models.TextField(blank=True, help_text='Comma-separated list of technologies used (e.g. Python, React, AWS).'),
        ),
    ]
