# Generated by Django 4.2.6 on 2026-04-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_company_industry_company_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='avg_salary_range',
            field=models.CharField(blank=True, help_text='e.g. $120k-$200k', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='careers_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='culture_notes',
            field=models.TextField(blank=True, help_text='Culture and work environment details.'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the company.'),
        ),
        migrations.AddField(
            model_name='company',
            name='employee_count',
            field=models.CharField(blank=True, help_text='e.g. 10000+, 500-1000', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='interview_process',
            field=models.TextField(blank=True, help_text='Detailed interview process and tips.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_role',
            field=models.CharField(blank=True, help_text='Current job title', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.CharField(blank=True, help_text='Highest education (e.g. B.Tech CS, M.S. AI)', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.IntegerField(default=0, help_text='Years of professional experience'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='Portfolio URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_work_style',
            field=models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site'), ('', 'Not specified')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of skills'),
        ),
    ]
